// ===== CONSTANTES GLOBAIS =====
const AUTHORIZED_GUILD_ID = process.env.GUILD_ID || "1438658038612623534";
const DASHBOARD_ROLE_ID = process.env.DASHBOARD_ROLE_ID || "1464264578773811301";

// Discord OAuth2
const DISCORD_CLIENT_ID = process.env.DISCORD_CLIENT_ID;
const DISCORD_CLIENT_SECRET = process.env.DISCORD_CLIENT_SECRET;
const DISCORD_REDIRECT_URI = process.env.DISCORD_REDIRECT_URI;
const JWT_SECRET = process.env.JWT_SECRET || 'kisekai-secret-key';

// Cache TTLs
const USER_PROFILE_CACHE_TTL = 5 * 60 * 1000; // 5 min
const STATS_CACHE_TTL = 15 * 1000; // 15s

module.exports = {
  AUTHORIZED_GUILD_ID,
  DASHBOARD_ROLE_ID,
  DISCORD_CLIENT_ID,
  DISCORD_CLIENT_SECRET,
  DISCORD_REDIRECT_URI,
  JWT_SECRET,
  USER_PROFILE_CACHE_TTL,
  STATS_CACHE_TTL
};